### ISSUE TITLE
How to build this object on ubuntu?

### ISSUE THREAD

**Issue by Superlee506** [ZheyuanXie/CUDA-Path-Tracer-Denoising#5]
Hi, YuanXie,
This project is a great work. I've learned a lot from it. But how can I build this project on Ubuntu 16.04?

**Comment by ZheyuanXie** [comment]
Hi, the project has only been built and tested on Windows. 
However, theoretically, it can be built on Ubuntu Linux. You can try generating UNIX Makefile with CMake and see if it works.

**Comment by Superlee506** [comment]
@ZheyuanXie Thanks, I will have a try. Before I do that, I want to know which version of glm/glew do you used?

**Comment by blockspacer** [comment]
Install CUDA as in https://www.pugetsystems.com/labs/hpc/How-to-install-CUDA-9-2-on-Ubuntu-18-04-1184/

```bash
git clone https://github.com/ZheyuanXie/CUDA-Path-Tracer-Denoising.git --recursive
cd CUDA-Path-Tracer-Denoising/
mkdir build
cd build
cmake ..
sudo apt-get install libglfw3
sudo apt-get install libglfw3-dev
sudo apt-get install libglew-dev
 cmake --build .
./bin/cis565_path_tracer /media/denis/hdd11/CUDA-Path-Tracer-Denoising/scenes/room.txt
```
