### ISSUE TITLE
The code differs from the original paper(svgf)

### ISSUE THREAD

**Issue by Superlee506** [ZheyuanXie/CUDA-Path-Tracer-Denoising#6]
Hi, sorry to trouble you again, when I refer to the code, I have some questions as follows：

1. The g-buffer is not generated from the rasterized and it seems come from the RT which is differet from the original paper.
2.  Do you reconstruct the direct and indirect light seperately?
3. The g-buffer doesn't contrain the motion vector, so it could just render the static scene.

Any suggestion should be appreciated.

**Comment by ZheyuanXie** [comment]
1. Yes. The project did not populate the g-buffer with a rasterizer. It uses the result of RT first intersection which produces the same depth (position), normal, and albedo info.
2. No. This is intended to be future work.
3.  I use the view matrix from the previous frame to compute reprojected pixel locations, which works out the same way as the original paper. The project supports static scene (no moving object) with moving camera.

**Comment by Superlee506** [comment]
@ZheyuanXie Thanks~
